"""BayesIQ Dashboard — Generated by BayesIQ Data Audit Kit."""

import json
import os
import re

import pandas as pd
import plotly.express as px
import streamlit as st

st.set_page_config(page_title="BayesIQ Dashboard", layout="wide")

@st.cache_data
def load_data(path):
    """Load and clean the dataset from a file path."""
    if path.endswith('.parquet'):
        df = pd.read_parquet(path)
    else:
        df = pd.read_csv(path)

    if "payment_date" in df.columns:
        df["payment_date"] = pd.to_datetime(df["payment_date"], utc=True)

    # Remove near-duplicate rows
    dedup_cols = ["unit_id", "tenant_id", "property_id", "unit_type", "lease_type", "payment_method", "payment_date", "due_date", "amount_due", "amount_paid", "late_fee", "days_late", "delinquent_flag", "vacancy_flag", "payment_flag", "billed_flag", "collected_flag", "late_flag"]
    before = len(df)
    df = df.drop_duplicates(subset=dedup_cols, keep='first')
    after = len(df)
    df.attrs["rows_deduped"] = before - after

    return df


@st.cache_data
def load_uploaded(file):
    """Load and clean a dataset from an uploaded file."""
    if file.name.endswith('.parquet'):
        df = pd.read_parquet(file)
    else:
        df = pd.read_csv(file)

    if "payment_date" in df.columns:
        df["payment_date"] = pd.to_datetime(df["payment_date"], utc=True)

    # Remove near-duplicate rows
    dedup_cols = ["unit_id", "tenant_id", "property_id", "unit_type", "lease_type", "payment_method", "payment_date", "due_date", "amount_due", "amount_paid", "late_fee", "days_late", "delinquent_flag", "vacancy_flag", "payment_flag", "billed_flag", "collected_flag", "late_flag"]
    before = len(df)
    df = df.drop_duplicates(subset=dedup_cols, keep='first')
    after = len(df)
    df.attrs["rows_deduped"] = before - after

    return df


def main():
    st.title("BayesIQ Data Dashboard")

    st.sidebar.header("Data Source")
    uploaded_file = st.sidebar.file_uploader(
        "Upload CSV or Parquet",
        type=["csv", "parquet", "pq"],
        help="Drag and drop a file here, or click to browse."
    )
    default_path = "data/raw_month_3.csv"
    data_path = st.sidebar.text_input("Or enter file path", value=default_path)

    # Load from upload or path
    df = None
    if uploaded_file is not None:
        try:
            df = load_uploaded(uploaded_file)
        except Exception as e:
            st.error(f"Could not load uploaded file: {e}")
            return
    elif data_path:
        try:
            df = load_data(data_path)
        except Exception as e:
            st.error(f"Could not load dataset: {e}")
            return
    else:
        st.info("Upload a file or enter a dataset path in the sidebar to get started.")
        return

    # Auto-detect period: weekly for short datasets, monthly otherwise
    _period = "M"
    if "payment_date" in df.columns:
        _ts_range = df["payment_date"].max() - df["payment_date"].min()
        if _ts_range.days <= 45:
            _period = "W"

    # --- Column Role Wizard ---
    roles_file = os.path.join(os.path.dirname(__file__), "column_roles_resolved.json")
    saved_roles = {}
    if os.path.exists(roles_file):
        with open(roles_file) as _f:
            saved_roles = json.load(_f)

    ambiguous_cols = ["property_id", "unit_type"]
    unresolved = [c for c in ambiguous_cols if c not in saved_roles]

    if unresolved:
        st.info("Some columns contain embedded numbers (e.g. \"5 Pack\", \"8 MILLIGRAM\"). Tell us how to use them.")
        with st.expander("Configure column roles", expanded=True):
            wizard_roles = {}
            st.markdown("**property_id** — e.g. PROP-001, PROP-002, PROP-003")
            property_id_role = st.radio(
                "Role for property_id",
                ['Use as filter (categorical)', 'Use as ordered axis (sort by number)', 'Use as numeric multiplier', 'Ignore this column'],
                index=0,
                key="wizard_property_id",
                horizontal=True,
            )
            wizard_roles["property_id"] = {"role": property_id_role}
            if "multiplier" in property_id_role.lower():
                property_id_target = st.selectbox(
                    "Multiply against",
                    ["amount_due", "amount_paid", "late_fee", "days_late", "delinquent_flag", "vacancy_flag", "payment_flag", "billed_flag", "collected_flag", "late_flag"],
                    index=0,
                    key="wizard_property_id_target",
                )
                wizard_roles["property_id"]["multiply_against"] = property_id_target

            st.markdown("**unit_type** — e.g. 1BR, 2BR, 3BR")
            unit_type_role = st.radio(
                "Role for unit_type",
                ['Use as filter (categorical)', 'Use as numeric multiplier', 'Use as ordered axis (sort by number)', 'Ignore this column'],
                index=0,
                key="wizard_unit_type",
                horizontal=True,
            )
            wizard_roles["unit_type"] = {"role": unit_type_role}
            if "multiplier" in unit_type_role.lower():
                unit_type_target = st.selectbox(
                    "Multiply against",
                    ["amount_due", "amount_paid", "late_fee", "days_late", "delinquent_flag", "vacancy_flag", "payment_flag", "billed_flag", "collected_flag", "late_flag"],
                    index=0,
                    key="wizard_unit_type_target",
                )
                wizard_roles["unit_type"]["multiply_against"] = unit_type_target

            if st.button("Save column roles", type="primary"):
                saved_roles.update(wizard_roles)
                with open(roles_file, 'w') as _f:
                    json.dump(saved_roles, _f, indent=2)
                st.success("Column roles saved. Reloading...")
                st.rerun()

    # Apply resolved column roles
    for col_name, role_info in saved_roles.items():
        if col_name not in df.columns:
            continue
        role_str = role_info.get("role", "")
        if "multiplier" in role_str.lower():
            target = role_info.get("multiply_against")
            if target and target in df.columns:
                nums = df[col_name].astype(str).str.extract(r"(\d+(?:\.\d+)?)", expand=False).astype(float)
                derived_name = role_info.get("derived_metric_name", f"{target}_x_{col_name}")
                df[derived_name] = df[target] * nums
        elif "ordered" in role_str.lower() or "ordinal" in role_str.lower():
            sort_order = df[col_name].drop_duplicates().to_frame()
            sort_order["_sort"] = sort_order[col_name].astype(str).str.extract(r"(\d+(?:\.\d+)?)", expand=False).astype(float)
            sort_order = sort_order.sort_values("_sort")[col_name].tolist()
            df[col_name] = pd.Categorical(df[col_name], categories=sort_order, ordered=True)

    # --- Sidebar Filters ---
    st.sidebar.header("Filters")

    if "payment_date" in df.columns:
        min_date = df["payment_date"].min().date()
        max_date = df["payment_date"].max().date()
        date_range = st.sidebar.date_input(
            "Date Range",
            value=(min_date, max_date),
            min_value=min_date,
            max_value=max_date,
        )
        if len(date_range) == 2:
            df = df[(df["payment_date"].dt.date >= date_range[0]) &
                    (df["payment_date"].dt.date <= date_range[1])]

    if "unit_type" in df.columns:
        unit_type_opts = sorted(df["unit_type"].dropna().unique().tolist())
        unit_type_sel = st.sidebar.multiselect(
            "unit_type",
            options=unit_type_opts,
            default=unit_type_opts,
        )
        df = df[df["unit_type"].isin(unit_type_sel)]

    if "lease_type" in df.columns:
        lease_type_opts = sorted(df["lease_type"].dropna().unique().tolist())
        lease_type_sel = st.sidebar.multiselect(
            "lease_type",
            options=lease_type_opts,
            default=lease_type_opts,
        )
        df = df[df["lease_type"].isin(lease_type_sel)]

    if "payment_method" in df.columns:
        payment_method_opts = sorted(df["payment_method"].dropna().unique().tolist())
        payment_method_sel = st.sidebar.multiselect(
            "payment_method",
            options=payment_method_opts,
            default=payment_method_opts,
        )
        df = df[df["payment_method"].isin(payment_method_sel)]

    if "late_fee" in df.columns:
        late_fee_opts = sorted(df["late_fee"].dropna().unique().tolist())
        late_fee_sel = st.sidebar.multiselect(
            "late_fee",
            options=late_fee_opts,
            default=late_fee_opts,
        )
        df = df[df["late_fee"].isin(late_fee_sel)]

    if "days_late" in df.columns:
        days_late_opts = sorted(df["days_late"].dropna().unique().tolist())
        days_late_sel = st.sidebar.multiselect(
            "days_late",
            options=days_late_opts,
            default=days_late_opts,
        )
        df = df[df["days_late"].isin(days_late_sel)]

    if "delinquent_flag" in df.columns:
        delinquent_flag_opts = sorted(df["delinquent_flag"].dropna().unique().tolist())
        delinquent_flag_sel = st.sidebar.multiselect(
            "delinquent_flag",
            options=delinquent_flag_opts,
            default=delinquent_flag_opts,
        )
        df = df[df["delinquent_flag"].isin(delinquent_flag_sel)]

    if "vacancy_flag" in df.columns:
        vacancy_flag_opts = sorted(df["vacancy_flag"].dropna().unique().tolist())
        vacancy_flag_sel = st.sidebar.multiselect(
            "vacancy_flag",
            options=vacancy_flag_opts,
            default=vacancy_flag_opts,
        )
        df = df[df["vacancy_flag"].isin(vacancy_flag_sel)]

    if "payment_flag" in df.columns:
        payment_flag_opts = sorted(df["payment_flag"].dropna().unique().tolist())
        payment_flag_sel = st.sidebar.multiselect(
            "payment_flag",
            options=payment_flag_opts,
            default=payment_flag_opts,
        )
        df = df[df["payment_flag"].isin(payment_flag_sel)]

    if "collected_flag" in df.columns:
        collected_flag_opts = sorted(df["collected_flag"].dropna().unique().tolist())
        collected_flag_sel = st.sidebar.multiselect(
            "collected_flag",
            options=collected_flag_opts,
            default=collected_flag_opts,
        )
        df = df[df["collected_flag"].isin(collected_flag_sel)]

    if "late_flag" in df.columns:
        late_flag_opts = sorted(df["late_flag"].dropna().unique().tolist())
        late_flag_sel = st.sidebar.multiselect(
            "late_flag",
            options=late_flag_opts,
            default=late_flag_opts,
        )
        df = df[df["late_flag"].isin(late_flag_sel)]

    st.sidebar.metric("Rows (filtered)", f"{len(df):,}")
    deduped = df.attrs.get("rows_deduped", 0)
    if deduped:
        st.sidebar.metric("Rows deduped", f"{deduped:,}")

    tabs = st.tabs(["Metrics", "Data Quality", "Raw Data"])

    with tabs[0]:
        st.header("Business Metrics")

        st.subheader("Collection Rate")

        _dim_options_collection_rate = ['unit_type', 'lease_type', 'payment_method', 'late_fee', 'days_late', 'delinquent_flag', 'vacancy_flag', 'payment_flag', 'collected_flag', 'late_flag']
        _sel_dim_collection_rate = st.selectbox(
            "Break down by", ["(none)"] + _dim_options_collection_rate,
            key="dim_picker_collection_rate")

        num_df = df[(df["collected_flag"] == 1)]
        den_df = df[(df["billed_flag"] == 1)]
        den_grouped = den_df.groupby(den_df["payment_date"].dt.to_period(_period)).size()
        num_grouped = num_df.groupby(num_df["payment_date"].dt.to_period(_period)).size().reindex(den_grouped.index, fill_value=0)
        ratio_df = (num_grouped / den_grouped).fillna(0).reset_index()
        ratio_df.columns = ["period", "collection_rate"]
        ratio_df["period"] = ratio_df["period"].astype(str)

        if ratio_df.empty:
            st.info("No data for Collection Rate in this period.")
        else:
            fig = px.line(ratio_df, x="period", y="collection_rate", title="Collection Rate Over Time", markers=True)
            st.plotly_chart(fig, use_container_width=True)

        if _sel_dim_collection_rate != "(none)":
            _dim_col = _sel_dim_collection_rate
            _dim_label = _dim_col.replace("_", " ").title()
            if _dim_col in num_df.columns:
                num_dim = num_df.groupby([num_df["payment_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                den_dim = den_df.groupby([den_df["payment_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                ratio_dim = (num_dim / den_dim).stack().reset_index()
                ratio_dim.columns = ["period", _dim_col, "collection_rate"]
                ratio_dim["period"] = ratio_dim["period"].astype(str)
                fig2 = px.line(ratio_dim, x="period", y="collection_rate", color=_dim_col, title=f"Collection Rate by {_dim_label}", markers=True)
                st.plotly_chart(fig2, use_container_width=True)

        st.divider()

        st.subheader("Delinquency")

        _dim_options_delinquency = ['unit_type', 'lease_type', 'payment_method', 'late_fee', 'days_late', 'delinquent_flag', 'vacancy_flag', 'payment_flag', 'collected_flag', 'late_flag']
        _sel_dim_delinquency = st.selectbox(
            "Break down by", ["(none)"] + _dim_options_delinquency,
            key="dim_picker_delinquency")

        num_df = df[(df["delinquent_flag"] == 1)]
        den_df = df[(df["billed_flag"] == 1)]
        den_grouped = den_df.groupby(den_df["payment_date"].dt.to_period(_period)).size()
        num_grouped = num_df.groupby(num_df["payment_date"].dt.to_period(_period)).size().reindex(den_grouped.index, fill_value=0)
        ratio_df = (num_grouped / den_grouped).fillna(0).reset_index()
        ratio_df.columns = ["period", "delinquency"]
        ratio_df["period"] = ratio_df["period"].astype(str)

        if ratio_df.empty:
            st.info("No data for Delinquency in this period.")
        else:
            fig = px.line(ratio_df, x="period", y="delinquency", title="Delinquency Over Time", markers=True)
            st.plotly_chart(fig, use_container_width=True)

        if _sel_dim_delinquency != "(none)":
            _dim_col = _sel_dim_delinquency
            _dim_label = _dim_col.replace("_", " ").title()
            if _dim_col in num_df.columns:
                num_dim = num_df.groupby([num_df["payment_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                den_dim = den_df.groupby([den_df["payment_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                ratio_dim = (num_dim / den_dim).stack().reset_index()
                ratio_dim.columns = ["period", _dim_col, "delinquency"]
                ratio_dim["period"] = ratio_dim["period"].astype(str)
                fig2 = px.line(ratio_dim, x="period", y="delinquency", color=_dim_col, title=f"Delinquency by {_dim_label}", markers=True)
                st.plotly_chart(fig2, use_container_width=True)

        st.divider()

        st.subheader("Vacancy Loss")

        _dim_options_vacancy_loss = ['unit_type', 'lease_type', 'payment_method', 'late_fee', 'days_late', 'delinquent_flag', 'vacancy_flag', 'payment_flag', 'collected_flag', 'late_flag']
        _sel_dim_vacancy_loss = st.selectbox(
            "Break down by", ["(none)"] + _dim_options_vacancy_loss,
            key="dim_picker_vacancy_loss")

        num_df = df[(df["vacancy_flag"] == 1)]
        den_df = df[(df["billed_flag"] == 1)]
        den_grouped = den_df.groupby(den_df["payment_date"].dt.to_period(_period)).size()
        num_grouped = num_df.groupby(num_df["payment_date"].dt.to_period(_period)).size().reindex(den_grouped.index, fill_value=0)
        ratio_df = (num_grouped / den_grouped).fillna(0).reset_index()
        ratio_df.columns = ["period", "vacancy_loss"]
        ratio_df["period"] = ratio_df["period"].astype(str)

        if ratio_df.empty:
            st.info("No data for Vacancy Loss in this period.")
        else:
            fig = px.line(ratio_df, x="period", y="vacancy_loss", title="Vacancy Loss Over Time", markers=True)
            st.plotly_chart(fig, use_container_width=True)

        if _sel_dim_vacancy_loss != "(none)":
            _dim_col = _sel_dim_vacancy_loss
            _dim_label = _dim_col.replace("_", " ").title()
            if _dim_col in num_df.columns:
                num_dim = num_df.groupby([num_df["payment_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                den_dim = den_df.groupby([den_df["payment_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                ratio_dim = (num_dim / den_dim).stack().reset_index()
                ratio_dim.columns = ["period", _dim_col, "vacancy_loss"]
                ratio_dim["period"] = ratio_dim["period"].astype(str)
                fig2 = px.line(ratio_dim, x="period", y="vacancy_loss", color=_dim_col, title=f"Vacancy Loss by {_dim_label}", markers=True)
                st.plotly_chart(fig2, use_container_width=True)

        st.divider()

        st.subheader("Late Payment Rate")

        _dim_options_late_payment_rate = ['unit_type', 'lease_type', 'payment_method', 'late_fee', 'days_late', 'delinquent_flag', 'vacancy_flag', 'payment_flag', 'collected_flag', 'late_flag']
        _sel_dim_late_payment_rate = st.selectbox(
            "Break down by", ["(none)"] + _dim_options_late_payment_rate,
            key="dim_picker_late_payment_rate")

        num_df = df[(df["late_flag"] == 1)]
        den_df = df[(df["payment_flag"] == 1)]
        den_grouped = den_df.groupby(den_df["payment_date"].dt.to_period(_period)).size()
        num_grouped = num_df.groupby(num_df["payment_date"].dt.to_period(_period)).size().reindex(den_grouped.index, fill_value=0)
        ratio_df = (num_grouped / den_grouped).fillna(0).reset_index()
        ratio_df.columns = ["period", "late_payment_rate"]
        ratio_df["period"] = ratio_df["period"].astype(str)

        if ratio_df.empty:
            st.info("No data for Late Payment Rate in this period.")
        else:
            fig = px.line(ratio_df, x="period", y="late_payment_rate", title="Late Payment Rate Over Time", markers=True)
            st.plotly_chart(fig, use_container_width=True)

        if _sel_dim_late_payment_rate != "(none)":
            _dim_col = _sel_dim_late_payment_rate
            _dim_label = _dim_col.replace("_", " ").title()
            if _dim_col in num_df.columns:
                num_dim = num_df.groupby([num_df["payment_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                den_dim = den_df.groupby([den_df["payment_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                ratio_dim = (num_dim / den_dim).stack().reset_index()
                ratio_dim.columns = ["period", _dim_col, "late_payment_rate"]
                ratio_dim["period"] = ratio_dim["period"].astype(str)
                fig2 = px.line(ratio_dim, x="period", y="late_payment_rate", color=_dim_col, title=f"Late Payment Rate by {_dim_label}", markers=True)
                st.plotly_chart(fig2, use_container_width=True)

        st.divider()

        st.subheader("Rent Growth")

        _dim_options_rent_growth = ['unit_type', 'lease_type', 'payment_method', 'late_fee', 'days_late', 'delinquent_flag', 'vacancy_flag', 'payment_flag', 'collected_flag', 'late_flag']
        _sel_dim_rent_growth = st.selectbox(
            "Break down by", ["(none)"] + _dim_options_rent_growth,
            key="dim_picker_rent_growth")

        metric_df = df
        if "amount_due" not in metric_df.columns:
            st.warning("Column \"amount_due\" not found in data — skipping Rent Growth.")
        else:
            grouped = metric_df.groupby(metric_df["payment_date"].dt.to_period(_period))["amount_due"].mean().reset_index()
            grouped.columns = ["period", "rent_growth"]
            grouped["period"] = grouped["period"].astype(str)

            fig = px.line(grouped, x="period", y="rent_growth", title="Rent Growth Over Time", markers=True)
            st.plotly_chart(fig, use_container_width=True)

            # Dimension breakdown
        if _sel_dim_rent_growth != "(none)":
            _dim_col = _sel_dim_rent_growth
            _dim_label = _dim_col.replace("_", " ").title()
            if _dim_col in metric_df.columns and "amount_due" in metric_df.columns:
                dim_grouped = metric_df.groupby([metric_df["payment_date"].dt.to_period(_period), _dim_col])["amount_due"].mean().reset_index()
                dim_grouped.columns = ["period", _dim_col, "rent_growth"]
                dim_grouped["period"] = dim_grouped["period"].astype(str)
                fig2 = px.line(dim_grouped, x="period", y="rent_growth", color=_dim_col, title=f"Rent Growth by {_dim_label}", markers=True)
                st.plotly_chart(fig2, use_container_width=True)


        st.divider()

    with tabs[1]:
        st.header("Data Quality Summary")
        st.metric("Total Issues Found", 4)

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Critical", 0)
        col2.metric("High", 3)
        col3.metric("Medium", 1)
        col4.metric("Low", 0)

        st.info("This dashboard applies automatic cleaning: value canonicalization and near-duplicate deduplication. The issues below were detected in the raw data before cleaning.")

        st.subheader("Findings")
        st.markdown("**1. [HIGH]** vacancy_loss misreported for 2025-12 (off by +100.0%) (1 rows)")
        st.markdown("**2. [HIGH]** Near-duplicate rows detected (60 rows)")
        st.markdown("**3. [HIGH]** Null values in required column: tenant_id (32 rows)")
        st.markdown("**4. [MEDIUM]** delinquency misreported for 2025-12 (off by -8.7%) (1 rows)")

    with tabs[2]:
        st.header("Raw Data")
        st.dataframe(df.head(1000), use_container_width=True)


if __name__ == "__main__":
    main()
